(() => {
  const select = document.querySelector('[data-language]');
  if (!select) return;
  const page = document.body.classList.contains('collection-page') ? 'form' : 'landing';
  const t = {
    form: {
      fr: {lang:'fr',top:'CAS ATELIER ANONYME',title:'Documenter un<br><em>cas atelier.</em>',progress:['Véhicule','Panne & DTC','Résolution'],context:'CONTEXTE',vehicle:'Quel véhicule ?',signal:'SIGNAL INITIAL',observed:'Qu’avez-vous observé ?',conclusion:'CONCLUSION TERRAIN',resolved:'Qu’est-ce qui a réglé le problème ?',add:'Ajouter le code',send:'Envoyer le cas',sending:'ENVOI ORVECT',format:'Formats TXT lisible + JSON structuré pour la base IA.',done:'Merci pour le retour terrain.',newCase:'Nouveau cas',text:'Télécharger TXT',json:'Télécharger JSON',share:'Partager les fichiers',help:'Besoin d’aide ?',labels:['Symptômes / plainte client','Conditions d’apparition','Contrôles et recherches effectués','Intervention réalisée','Cause réelle identifiée','Pièces remplacées','Résultat final','Comment avez-vous confirmé le résultat ?','Information utile à un autre garage'],consent:'Je confirme que ce retour anonyme ne contient ni nom, ni e-mail, ni plaque d’immatriculation, ni VIN, et qu’ORVECT peut l’utiliser pour améliorer ses outils de diagnostic.'},
      en: {lang:'en',top:'ANONYMOUS WORKSHOP CASE',title:'Document a<br><em>workshop case.</em>',progress:['Vehicle','Fault & DTC','Resolution'],context:'CONTEXT',vehicle:'Which vehicle?',signal:'INITIAL SIGNAL',observed:'What did you observe?',conclusion:'FIELD CONCLUSION',resolved:'What solved the problem?',add:'Add code',send:'Send case',sending:'SEND TO ORVECT',format:'Readable TXT + structured JSON for the AI dataset.',done:'Thank you for the field report.',newCase:'New case',text:'Download TXT',json:'Download JSON',share:'Share files',help:'Need help?',labels:['Symptoms / customer complaint','Occurrence conditions','Checks and investigation performed','Repair performed','Actual root cause','Parts replaced','Final outcome','How did you confirm the result?','Useful information for another workshop'],consent:'I confirm this anonymous report contains no name, email, registration plate or VIN, and that ORVECT may use it to improve diagnostic tools.'},
      sv: {lang:'sv',top:'ANONYMT VERKSTADSÄRENDE',title:'Dokumentera ett<br><em>verkstadsärende.</em>',progress:['Fordon','Fel & DTC','Lösning'],context:'KONTEXT',vehicle:'Vilket fordon?',signal:'URSPRUNGLIG SIGNAL',observed:'Vad observerade ni?',conclusion:'SLUTSATS FRÅN VERKSTADEN',resolved:'Vad löste problemet?',add:'Lägg till kod',send:'Skicka ärendet',sending:'SKICKA TILL ORVECT',format:'Läsbar TXT + strukturerad JSON för AI-datasetet.',done:'Tack för verkstadsrapporten.',newCase:'Nytt ärende',text:'Ladda ner TXT',json:'Ladda ner JSON',share:'Dela filer',help:'Behöver du hjälp?',labels:['Symtom / kundens beskrivning','När uppstod felet?','Utförda kontroller och felsökning','Utförd åtgärd','Fastställd grundorsak','Bytta delar','Slutligt resultat','Hur bekräftade ni resultatet?','Användbar information för en annan verkstad'],consent:'Jag bekräftar att denna anonyma rapport inte innehåller namn, e-post, registreringsnummer eller VIN, och att ORVECT får använda den för att förbättra diagnostikverktyg.'}
    },
    landing: {
      fr:{lang:'fr',nav:['L’approche','Le prototype','La vision'],cta:'Nous contacter',eyebrow:'PENSÉE INDÉPENDANTE. INTELLIGENCE AUTOMOBILE.',title:'Au-delà<br>du code<br><span>d’erreur.</span>',lead:'Une nouvelle direction pour le diagnostic automobile.<br>Fondée sur le contexte. Ancrée dans les preuves.<br>Le technicien reste aux commandes.',explore:'Explorer le prototype',approach:'Notre approche',section1:'01 / L’APPROCHE',heading1:'Un code est<br>le début.<br><span>Pas la réponse.</span>',section2:'02 / DANS LE PROTOTYPE',heading2:'La confiance commence<br>par savoir<br><span>ce que l’on ignore.</span>',section3:'03 / CONSTRUIT AVEC DES LIMITES',heading3:'Intelligence.<br><span>Avec structure.</span>',section4:'04 / LA DIRECTION',contact:'Faire avancer<br>le diagnostic.',contactCta:'Parler avec nous',help:'Besoin d’aide ?'},
      en:{lang:'en',nav:['The approach','The prototype','The vision'],cta:"Let's talk",eyebrow:'INDEPENDENT THINKING. AUTOMOTIVE INTELLIGENCE.',title:'Beyond<br>the fault<br><span>code.</span>',lead:'A new direction for automotive diagnostics.<br>Built around context. Grounded in evidence.<br>Designed to keep the technician in control.',explore:'Explore the prototype',approach:'Our approach',section1:'01 / THE APPROACH',heading1:'A code is<br>the beginning.<br><span>Not the answer.</span>',section2:'02 / INSIDE THE PROTOTYPE',heading2:"Confidence starts<br>with knowing<br><span>what you don\'t know.</span>",section3:'03 / BUILT WITH BOUNDARIES',heading3:'Intelligence.<br><span>With structure.</span>',section4:'04 / THE DIRECTION',contact:"Let's move<br>diagnostics<br><span>forward.</span>",contactCta:'Start a conversation',help:'Need help?'},
      sv:{lang:'sv',nav:['Arbetssättet','Prototypen','Visionen'],cta:'Kontakta oss',eyebrow:'SJÄLVSTÄNDIGT TÄNKANDE. AUTOMOTIV INTELLIGENS.',title:'Bortom<br>fel<span>koden.</span>',lead:'En ny riktning för fordonsdiagnostik.<br>Byggd kring kontext. Förankrad i bevis.<br>Teknikern behåller kontrollen.',explore:'Utforska prototypen',approach:'Vårt arbetssätt',section1:'01 / ARBETSSÄTTET',heading1:'En kod är<br>början.<br><span>Inte svaret.</span>',section2:'02 / I PROTOTYPEN',heading2:'Förtroende börjar<br>med att veta<br><span>vad du inte vet.</span>',section3:'03 / BYGGT MED GRÄNSER',heading3:'Intelligens.<br><span>Med struktur.</span>',section4:'04 / RIKTNINGEN',contact:'Ta diagnostiken<br><span>framåt.</span>',contactCta:'Starta en dialog',help:'Behöver du hjälp?'}
    }
  };
  const fallback='fr'; const initial=localStorage.getItem('orvect-language')||document.documentElement.lang||fallback; select.value=t[page][initial]?initial:fallback;
  const text=(s,v,html=false)=>{const n=document.querySelector(s);if(n)html?n.innerHTML=v:n.textContent=v;};
  const label=(name,v)=>{const n=document.querySelector(`[name="${name}"]`)?.closest('label')?.querySelector(':scope > span');if(n)n.textContent=v;};
  function applyForm(c){document.documentElement.lang=c.lang;text('.topbar-label',c.top);text('#pageTitle',c.title,true);document.querySelectorAll('[data-progress]').forEach((n,i)=>n.innerHTML=`<span>0${i+1}</span> ${c.progress[i]}`);text('#vehicle h2',c.vehicle);text('#fault h2',c.observed);text('#resolution h2',c.resolved);text('#vehicle .eyebrow',c.context);text('#fault .eyebrow',c.signal);text('#resolution .eyebrow',c.conclusion);['symptoms','conditions','diagnosticSteps','repairAction','rootCause','partsReplaced','outcome','verification','lessonLearned'].forEach((n,i)=>label(n,c.labels[i]));text('#addDtc',c.add);text('.submit-row .eyebrow',c.sending);text('.submit-row p:not(.eyebrow)',c.format);text('#caseForm .button.primary',c.send,true);text('.check span',c.consent,true);text('#successTitle',c.done);text('#downloadText',c.text);text('#downloadJson',c.json);text('#shareCase',c.share);text('#newCase',c.newCase);text('footer a',c.help);const m=document.querySelector('#dtcMeaning');if(m)m.placeholder=c.labels[0];const o=document.querySelector('[name="outcome"]');if(o)[...o.options].forEach((x,i)=>x.textContent=[[c.lang==='fr'?'Sélectionner':c.lang==='en'?'Select':'Välj'],[c.lang==='fr'?'Panne résolue':c.lang==='en'?'Problem solved':'Felet löst'],[c.lang==='fr'?'Partiellement résolue':c.lang==='en'?'Partially solved':'Delvis löst'],[c.lang==='fr'?'Non résolue':c.lang==='en'?'Unresolved':'Ej löst'],[c.lang==='fr'?'Résultat non vérifié':c.lang==='en'?'Result not verified':'Resultat ej verifierat']][i]);}
  function applyLanding(c){document.documentElement.lang=c.lang;text('nav a:nth-child(1)',c.nav[0]);text('nav a:nth-child(2)',c.nav[1]);text('nav a:nth-child(3)',c.nav[2]);text('.nav-cta',c.cta,true);text('.hero-copy .eyebrow',c.eyebrow,true);text('#hero-title',c.title,true);text('.hero-copy .lead',c.lead,true);text('.actions .primary',c.explore,true);text('.actions .text-link',c.approach,true);text('#approach .section-label span:first-child',c.section1);text('#approach-title',c.heading1,true);text('#product .section-label span:first-child',c.section2);text('#product-title',c.heading2,true);text('#architecture .section-label span:first-child',c.section3);text('#architecture-title',c.heading3,true);text('#vision .section-label span:first-child',c.section4);text('.contact h2',c.contact,true);text('.contact-cta',c.contactCta,true);text('footer .footer-top a[href^="mailto"]',c.help);}
  const apply=lang=>{const c=t[page][lang]||t[page][fallback];page==='form'?applyForm(c):applyLanding(c);localStorage.setItem('orvect-language',lang);}; select.addEventListener('change',()=>apply(select.value));apply(select.value);
})();
