"use client";

import Link from "next/link";
import {useCallback,useEffect,useState} from "react";
import {useParams} from "next/navigation";
import {FlowProgress,ProductLayout,SectionIntro,SourceLabel,StatusLabel} from "@/components/OrvectProduct";
import {API,api} from "@/services/api";
import type {DiagnosticDetail,SourceReference} from "@/types";

type ImageDraft={file:File;preview:string;category:string;description:string};
const sourceStatus:Record<string,string>={provided_by_database:"DÉFINITION EXACTE SOURCÉE",ai_general_knowledge_unverified:"CONNAISSANCE GÉNÉRALE NON VÉRIFIÉE",not_found:"DÉFINITION INDISPONIBLE"};
const imageUrl=(path:string)=>`${API}${path.replace(/^\/api(?=\/)/,"")}`;

export default function AIDiagnosticConsole(){
 const {id}=useParams<{id:string}>();const [detail,setDetail]=useState<DiagnosticDetail|null>(null),[account,setAccount]=useState<{email:string;role:string}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [resultState,setResultState]=useState<"positive"|"negative"|"inconclusive"|"unavailable"|"invalid"|"refused">("inconclusive"),[outcome,setOutcome]=useState(""),[comment,setComment]=useState("");
 const [newCode,setNewCode]=useState(""),[newNamespace,setNewNamespace]=useState("sae_obd2"),[newEcu,setNewEcu]=useState(""),[newStatus,setNewStatus]=useState<"active"|"intermittent"|"stored"|"unknown">("unknown");
 const [measureName,setMeasureName]=useState(""),[measureValue,setMeasureValue]=useState(""),[measureUnit,setMeasureUnit]=useState(""),[pendingImages,setPendingImages]=useState<ImageDraft[]>([]);
 const load=useCallback(async()=>{try{const [caseDetail,user]=await Promise.all([api.diagnostic(id),api.me()]);setDetail(caseDetail);setAccount(user);setError("")}catch(value){setError(value instanceof Error?value.message:"Chargement impossible")}},[id]);useEffect(()=>{load()},[load]);
 const current=detail?.steps.find(item=>item.status==="current");
 async function saveResult(){if(!current)return;if((resultState==="positive"||resultState==="negative")&&!outcome.trim())return setError("Décrivez le résultat informatif constaté.");setBusy(true);setError("");try{await api.submitStepResult(id,current.id,{state:resultState,outcome,measurement:null,unit:null,comment});await api.reanalyzeDiagnostic(id);setResultState("inconclusive");setOutcome("");setComment("");await load()}catch(value){setError(value instanceof Error?value.message:"Réévaluation impossible")}finally{setBusy(false)}}
 async function reanalyze(){setBusy(true);setError("");try{await api.reanalyzeDiagnostic(id);await load()}catch(value){setError(value instanceof Error?value.message:"Réévaluation impossible")}finally{setBusy(false)}}
 async function addFaultCode(){if(!newCode.trim())return setError("Saisissez un code défaut.");setBusy(true);setError("");try{await api.addFaultCodes(id,{fault_codes:[{namespace:newNamespace,code:newCode.trim().toUpperCase(),ecu:newEcu.trim()||null,status:newStatus,freeze_frame:{}}]});setNewCode("");setNewEcu("");setNewStatus("unknown");await api.reanalyzeDiagnostic(id);await load()}catch(value){setError(value instanceof Error?value.message:"Ajout du code impossible")}finally{setBusy(false)}}
 async function addMeasurementQuick(){if(!measureName.trim())return setError("Nommez la mesure.");setBusy(true);setError("");try{const numeric=Number(measureValue);await api.addMeasurement(id,{name:measureName,value:Number.isFinite(numeric)&&measureValue.trim()?numeric:measureValue,unit:measureUnit.trim()||null,conditions:"",source:"manual"});setMeasureName("");setMeasureValue("");setMeasureUnit("");await api.reanalyzeDiagnostic(id);await load()}catch(value){setError(value instanceof Error?value.message:"Ajout de la mesure impossible")}finally{setBusy(false)}}
 function addPendingImages(list:FileList|File[]){const source=Array.from(list);const accepted=source.filter(file=>["image/jpeg","image/png","image/webp"].includes(file.type)&&file.size<=10*1024*1024);setPendingImages(current=>[...current,...accepted.slice(0,8-current.length).map(file=>({file,preview:URL.createObjectURL(file),category:"engine_bay",description:""}))]);if(accepted.length!==source.length)setError("Fichier refusé : JPEG, PNG ou WebP, 10 Mio maximum.")}
 function removePendingImage(index:number){setPendingImages(current=>{URL.revokeObjectURL(current[index].preview);return current.filter((_,itemIndex)=>itemIndex!==index)})}
 async function uploadPendingImages(){if(!pendingImages.length)return;setBusy(true);setError("");try{for(const item of pendingImages){const data=new FormData();data.append("files",item.file);data.append("category",item.category);data.append("description",item.description);await api.uploadImages(id,data)}pendingImages.forEach(item=>URL.revokeObjectURL(item.preview));setPendingImages([]);await api.reanalyzeDiagnostic(id);await load()}catch(value){setError(value instanceof Error?value.message:"Ajout des photos impossible")}finally{setBusy(false)}}

 if(!detail)return <ProductLayout active={4}><div className="orvect-panel" role="status">{error||"Chargement de l’analyse…"}</div></ProductLayout>;
 const analysis=detail.analysis;
 if(!analysis)return <ProductLayout active={4} identity={account?`${account.email} · ${account.role}`:undefined}><div className="orvect-panel"><p className="orvect-label">04 / DIAGNOSTIC ASSISTÉ</p><h1 className="mt-5 text-4xl font-bold">{detail.analysis_status==="legacy_requires_review"?"Analyse historique conservée":"Analyse indisponible"}</h1><p className="mt-4 max-w-2xl text-slate-600">{detail.analysis_status==="legacy_requires_review"?"L’ancien résultat est conservé sans modification. Une revue humaine et une nouvelle analyse sont nécessaires.":"Le dossier existe, mais aucune sortie validée n’a été enregistrée."}</p>{error&&<Alert message={error}/>}<button className="orvect-button-primary mt-6" disabled={busy} onClick={reanalyze}>{busy?"Réévaluation…":"Relancer l’analyse"}</button></div></ProductLayout>;
 const unknown=analysis.safetyAssessment.status==="UNKNOWN"||analysis.safetyAssessment.humanReviewRequired;
 return <ProductLayout active={4} identity={account?`${account.email} · ${account.role}`:undefined}>
  <div className="space-y-6"><SectionIntro label={`04 / DIAGNOSTIC ASSISTÉ · DOSSIER ${id.slice(0,8).toUpperCase()}`} title={<>Avancer contrôle par contrôle.<br/>Expliquer chaque limite.</>} description="Le moteur diagnostic structure l’état. Le moteur de sécurité applique uniquement ses règles. Le LLM explique les faits admis : il ne décide ni du danger, ni d’un remplacement."/><FlowProgress active={4}/>{error&&<Alert message={error}/>}<StatusLabel tone={unknown?"signal":"dark"}>{analysis.safetyAssessment.status.replaceAll("_"," ")}{analysis.safetyAssessment.humanReviewRequired?" / HUMAN REVIEW REQUIRED":" / RÈGLE DÉTERMINISTE"}</StatusLabel>
   <div className="grid items-start gap-5 xl:grid-cols-3">
    <section className="orvect-panel space-y-5"><p className="orvect-label text-slate-500">CONTEXTE DU DOSSIER</p><h2 className="text-2xl font-medium">{detail.vehicle.make} {detail.vehicle.model}<br/><span className="text-slate-500">{detail.vehicle.engine_code?`Moteur ${detail.vehicle.engine_code}`:"Configuration partielle"}</span></h2><div className="text-sm leading-6"><p className="orvect-label">OBSERVÉ</p><p className="mt-2">{detail.case.customer_complaint||detail.case.current_summary||"Aucun symptôme documenté"}</p>{detail.case.appearance_circumstances&&<p>{detail.case.appearance_circumstances}</p>}</div>
     <div className="space-y-3">{analysis.interpretedFaultCodes.map(code=><article key={`${code.namespace}:${code.code}`} className="border border-orvect-alloy p-4"><div className="flex items-start justify-between gap-3"><strong className="font-mono text-xl">{code.code}</strong><span className="text-[10px] uppercase">{code.definitionType.replaceAll("_"," ")}</span></div><p className="mt-2 text-sm">{code.meaning}</p><p className="mt-2 text-[10px] uppercase text-slate-500">{sourceStatus[code.sourceStatus]||code.sourceStatus}</p>{code.sources.map(source=><Source key={source.source_id} source={source}/>)}</article>)}</div>
     <SourceLabel title={`SOURCES / ${analysis.interpretedFaultCodes.flatMap(code=>code.sources).length} ADMISE(S)`}>Compatibilité véhicule conservée par référence.<br/>Toute définition constructeur indisponible reste indisponible.</SourceLabel>
     <div><p className="orvect-label text-slate-500">INFORMATIONS MANQUANTES</p>{analysis.missingInformation.length?<ul className="mt-3 space-y-3 text-sm">{analysis.missingInformation.map(item=><li key={item.field} className="border-t border-orvect-alloy pt-3"><strong>{item.field}</strong><span className="block text-slate-500">{item.reason}</span></li>)}</ul>:<p className="mt-2 text-sm">Aucune information manquante signalée.</p>}</div>
    </section>

    <section className="orvect-panel-dark space-y-4"><p className="orvect-label text-orvect-alloy">PROCESSUS GUIDÉ</p><h2 className="text-2xl font-medium">Prochain contrôle</h2>{current?<><div className="bg-orvect-orange p-4 text-orvect-graphite"><p className="text-xs uppercase">ÉTAPE {current.step_order} · COURANTE</p><h3 className="mt-2 text-xl font-medium">{current.title}</h3><p className="mt-2 text-sm">{current.objective}</p></div><ol className="space-y-2">{current.instructions.map((instruction,index)=><li key={instruction} className="border border-white/25 p-3 text-sm"><span className="mr-2 text-orvect-orange">{String(index+1).padStart(2,"0")}</span>{instruction}</li>)}</ol>{current.safety_notes.length>0&&<div className="border border-orvect-orange p-3 text-sm"><strong>Sécurité déterministe</strong><ul className="mt-2 list-inside list-disc text-orvect-alloy">{current.safety_notes.map(note=><li key={note}>{note}</li>)}</ul></div>}<div className="border-t border-white/20 pt-4"><label className="orvect-field-label text-orvect-alloy" htmlFor="result-state">État du résultat</label><select id="result-state" className="orvect-field bg-orvect-graphite text-orvect-mineral" value={resultState} onChange={event=>setResultState(event.target.value as typeof resultState)}><option value="positive">Positive — informatif</option><option value="negative">Negative — informatif</option><option value="inconclusive">Inconclusive</option><option value="unavailable">Unavailable</option><option value="invalid">Invalid</option><option value="refused">Refused</option></select><label className="orvect-field-label mt-3 text-orvect-alloy" htmlFor="outcome">Résultat constaté</label><textarea id="outcome" className="orvect-field min-h-20 bg-orvect-graphite text-orvect-mineral" value={outcome} onChange={event=>setOutcome(event.target.value)} placeholder="Relevé ou observation"/><label className="orvect-field-label mt-3 text-orvect-alloy" htmlFor="comment">Commentaire technicien</label><textarea id="comment" className="orvect-field min-h-16 bg-orvect-graphite text-orvect-mineral" value={comment} onChange={event=>setComment(event.target.value)}/><button className="orvect-button-primary mt-4 w-full" disabled={busy||((resultState==="positive"||resultState==="negative")&&!outcome.trim())} onClick={saveResult}>{busy?"Réévaluation…":"Enregistrer et réévaluer"}</button></div></>:<><StatusLabel>AUCUN CONTRÔLE FIABLE PROPOSÉ</StatusLabel><p className="text-sm text-orvect-alloy">L’absence de règle ou de contexte ne sera pas remplacée par une réponse du LLM.</p></>}
    </section>

    <section className="orvect-panel space-y-5"><p className="orvect-label text-slate-500">ÉTAT DIAGNOSTIQUE</p><h2 className="text-4xl font-medium tracking-[-.04em]">{analysis.hypotheses.length} hypothèse{analysis.hypotheses.length===1?"":"s"}</h2>{analysis.hypotheses.length===0?<div className="text-sm leading-6"><p className="font-medium">INSUFFICIENT EVIDENCE</p><p>Vehicle configuration not sufficiently identified.</p><p>Manufacturer-specific definition unavailable.</p></div>:<div className="space-y-3">{analysis.hypotheses.map((hypothesis,index)=><article key={hypothesis.id} className="border border-orvect-alloy p-4"><p className="orvect-label">HYPOTHÈSE {index+1} · {hypothesis.verificationStatus.replaceAll("_"," ")}</p><h3 className="mt-2 font-medium">{hypothesis.label}</h3><p className="mt-2 text-sm text-slate-500">Confiance de cohérence : {Math.round(hypothesis.confidence*100)} %</p>{hypothesis.sources.map(source=><Source key={source.source_id} source={source}/>)}</article>)}</div>}<StatusLabel>GENERAL LLM KNOWLEDGE / NON VÉRIFIÉE</StatusLabel><div className="text-sm leading-6"><p>Aucune décision de roulage par le LLM.</p><p>Aucun niveau de danger par le LLM.</p><p>Aucune pièce à remplacer automatiquement.</p><p>Aucune cause définitivement confirmée.</p></div><div className="bg-orvect-graphite p-6 text-orvect-mineral"><h3 className="text-2xl font-medium">{analysis.safetyAssessment.humanReviewRequired?"Escalade humaine requise":"Safety Engine"}</h3><p className="mt-4 text-sm leading-6 text-orvect-alloy">{analysis.safetyAssessment.explanation}</p><p className="mt-3 text-[10px] uppercase text-orvect-alloy">Source de décision : {analysis.safetyAssessment.decisionSource}</p></div>
    </section>
   </div>

   <details className="border border-orvect-alloy"><summary className="cursor-pointer p-5 font-medium">Ajouter une preuve au dossier</summary><div className="grid gap-5 border-t border-orvect-alloy p-5 lg:grid-cols-3"><section><p className="orvect-label">CODE DÉFAUT</p><select className="orvect-field mt-3" value={newNamespace} onChange={event=>setNewNamespace(event.target.value)}><option value="sae_obd2">SAE / OBD-II</option><option value="vag_uds">VAG / UDS</option></select><input className="orvect-field mt-2 font-mono uppercase" value={newCode} onChange={event=>setNewCode(event.target.value)} placeholder="Identifiant"/><input className="orvect-field mt-2" value={newEcu} onChange={event=>setNewEcu(event.target.value)} placeholder="Calculateur"/><select className="orvect-field mt-2" value={newStatus} onChange={event=>setNewStatus(event.target.value as typeof newStatus)}><option value="unknown">Inconnu</option><option value="active">Actif</option><option value="intermittent">Intermittent</option><option value="stored">Mémorisé</option></select><button className="orvect-button-secondary mt-2 w-full" onClick={addFaultCode} disabled={busy}>Ajouter et réévaluer</button></section><section><p className="orvect-label">MESURE</p><input className="orvect-field mt-3" value={measureName} onChange={event=>setMeasureName(event.target.value)} placeholder="Nom"/><input className="orvect-field mt-2" value={measureValue} onChange={event=>setMeasureValue(event.target.value)} placeholder="Valeur"/><input className="orvect-field mt-2" value={measureUnit} onChange={event=>setMeasureUnit(event.target.value)} placeholder="Unité"/><button className="orvect-button-secondary mt-2 w-full" onClick={addMeasurementQuick} disabled={busy}>Ajouter et réévaluer</button></section><section><p className="orvect-label">PHOTO</p><label htmlFor="more-images" className="mt-3 flex min-h-24 cursor-pointer items-center justify-center border border-dashed border-orvect-alloy p-4 text-center text-sm">JPEG, PNG ou WebP</label><input id="more-images" className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={event=>event.target.files&&addPendingImages(event.target.files)}/>{pendingImages.map((item,index)=><div key={item.preview} className="mt-2 flex justify-between text-xs"><span className="truncate">{item.file.name}</span><button onClick={()=>removePendingImage(index)}>Retirer</button></div>)}<button className="orvect-button-secondary mt-2 w-full" onClick={uploadPendingImages} disabled={busy||!pendingImages.length}>Ajouter et réévaluer</button></section></div></details>
   {detail.images.length>0&&<section><p className="orvect-label">PREUVES VISUELLES</p><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{detail.images.map(image=><figure key={image.id} className="border border-orvect-alloy"><img src={imageUrl(image.url)} alt={image.description||`Image technique ${image.category}`} className="aspect-video w-full object-cover"/><figcaption className="p-3 text-xs">{image.description||image.category}</figcaption></figure>)}</div></section>}
   <div className="flex flex-wrap gap-3"><Link href="/diagnostics/new" className="orvect-button-secondary">Nouveau dossier</Link><button className="orvect-button-primary" disabled={busy} onClick={reanalyze}>{busy?"Réévaluation…":"Réévaluer le dossier"}</button></div>
  </div>
 </ProductLayout>
}

function Source({source}:{source:SourceReference}){return <div className="mt-3 border-t border-orvect-alloy pt-3 text-[10px] leading-4 text-slate-500"><span className="block">source_id: {source.source_id}</span><span className="block">{source.source_type} · {source.source_version} · {source.verified?"VÉRIFIÉE":"NON VÉRIFIÉE"}</span><span className="block">timestamp: {source.timestamp||"indisponible"}</span></div>}
function Alert({message}:{message:string}){return <div role="alert" className="mt-5 border border-red-600 bg-red-50 p-4 text-sm text-red-800"><strong>Action impossible.</strong> {message}</div>}
