"use client";

import Link from "next/link";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {FlowProgress,ProductLayout,SectionIntro,SourceLabel,StatusLabel} from "@/components/OrvectProduct";
import {api} from "@/services/api";
import type {Session,Vehicle,VehicleResolveResult} from "@/types";

type Measurement={name:string;value:string;unit:string;conditions:string};
type ImageDraft={file:File;preview:string;category:string;description:string};
type ManualVehicle={make:string;model:string;model_year:string;engine_code:string;engine_power_hp:string;transmission_code:string};
type Account={id:string;email:string;role:string;garage_id:string};
const emptyManual:ManualVehicle={make:"",model:"",model_year:"",engine_code:"",engine_power_hp:"",transmission_code:""};

export default function NewDiagnostic(){
 const router=useRouter();
 const [step,setStep]=useState(1),[account,setAccount]=useState<Account|null>(null),[vehicles,setVehicles]=useState<Vehicle[]>([]),[sessions,setSessions]=useState<Session[]>([]),[vehicleId,setVehicleId]=useState("");
 const [registration,setRegistration]=useState(""),[country,setCountry]=useState("FR"),[lookup,setLookup]=useState<VehicleResolveResult|null>(null),[candidateId,setCandidateId]=useState("");
 const [identifierMode,setIdentifierMode]=useState<"registration"|"vin">("registration"),[vin,setVin]=useState(""),[manualOpen,setManualOpen]=useState(false),[manual,setManual]=useState<ManualVehicle>(emptyManual);
 const [mileage,setMileage]=useState(""),[symptoms,setSymptoms]=useState(""),[circumstances,setCircumstances]=useState(""),[codes,setCodes]=useState(""),[namespace,setNamespace]=useState("sae_obd2"),[ecu,setEcu]=useState(""),[status,setStatus]=useState("unknown");
 const [measurements,setMeasurements]=useState<Measurement[]>([]),[measure,setMeasure]=useState<Measurement>({name:"",value:"",unit:"",conditions:""}),[images,setImages]=useState<ImageDraft[]>([]);
 const [draftId,setDraftId]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[uploadProgress,setUploadProgress]=useState(0);
 const parsedCodes=useMemo(()=>codes.split(/[ ,;\n]+/).map(value=>value.trim().toUpperCase()).filter(Boolean),[codes]);
 const vehicle=vehicles.find(item=>item.id===vehicleId);

 useEffect(()=>{Promise.all([api.vehicles(),api.sessions(),api.me()]).then(([v,s,u])=>{setVehicles(v);setSessions(s);setAccount(u)}).catch(value=>setError(value instanceof Error?value.message:"Chargement impossible"))},[]);
 function navigate(target:number){if(target===1||target<step){setError("");setNotice("");setStep(target)}}
 function startNew(){setVehicleId("");setLookup(null);setDraftId("");setError("");setNotice("");setStep(2)}
 async function identify(event:FormEvent){event.preventDefault();setBusy(true);setError("");setNotice("");setVehicleId("");setLookup(null);try{const body=identifierMode==="registration"?{registration,country_code:country}:{vin,country_code:country};const result=await api.resolveVehicle(body);const candidate=result.candidates?.[0];setLookup(result);setCandidateId(candidate?.id??"");const incomplete=!candidate?.engine_code;setManualOpen(incomplete);if(candidate&&incomplete)setManual({make:candidate.make??"",model:candidate.model??"",model_year:candidate.model_year?String(candidate.model_year):"",engine_code:"",engine_power_hp:candidate.engine_power_hp?String(candidate.engine_power_hp):"",transmission_code:candidate.transmission_code??""});if(incomplete)setNotice("Configuration incomplète : complétez uniquement les données vérifiées.")}catch(value){setError(value instanceof Error?value.message:"Identification impossible")}finally{setBusy(false)}}
 async function confirmVehicle(){if(!lookup?.resolution_id||(!candidateId&&!manualOpen))return;setBusy(true);setError("");try{if(lookup.status==="confirmed"&&lookup.vehicle_id&&!manualOpen){const next=await api.vehicles();setVehicles(next);setVehicleId(lookup.vehicle_id);setLookup(null);setStep(3);return}const corrections=manualOpen?Object.fromEntries(Object.entries(manual).filter(([,value])=>value!=="").map(([key,value])=>[key,["model_year","engine_power_hp"].includes(key)?Number(value):value])):{};if(manualOpen&&(!manual.make||!manual.model||!manual.engine_code))throw new Error("Marque, modèle et code moteur sont obligatoires pour confirmer manuellement.");const data=await api.confirmResolution(lookup.resolution_id,{candidate_id:manualOpen?null:candidateId,corrections,configuration_unknown:false,registration:registration||null,registration_country:country,technician_note:manualOpen?"Identité technique confirmée manuellement par le technicien.":null});const next=await api.vehicles();setVehicles(next);setVehicleId(data.vehicle.id);setLookup(null);setStep(3)}catch(value){setError(value instanceof Error?value.message:"Confirmation impossible")}finally{setBusy(false)}}
 function addMeasurement(){if(!measure.name.trim()||!measure.value.trim())return setError("Indiquez le nom et la valeur de la mesure.");setMeasurements(rows=>[...rows,measure]);setMeasure({name:"",value:"",unit:"",conditions:""});setError("")}
 function addImages(list:FileList|File[]){const source=Array.from(list);const accepted=source.filter(file=>["image/jpeg","image/png","image/webp"].includes(file.type)&&file.size<=10*1024*1024);setImages(current=>[...current,...accepted.slice(0,8-current.length).map(file=>({file,preview:URL.createObjectURL(file),category:"engine_bay",description:""}))]);if(accepted.length!==source.length)setError("Fichier refusé : JPEG, PNG ou WebP, 10 Mio maximum par image.")}
 function removeImage(index:number){setImages(current=>{URL.revokeObjectURL(current[index].preview);return current.filter((_,itemIndex)=>itemIndex!==index)})}
 function validateEvidence(){if(!vehicleId)throw new Error("Sélectionnez ou identifiez un véhicule.");const valid=namespace==="sae_obd2"?/^[PBCU][0-9A-F]{4}$/:/^[A-Z0-9][A-Z0-9._:/+\-]{0,79}$/;if(!parsedCodes.length||parsedCodes.some(code=>!valid.test(code)))throw new Error("Saisissez au moins un identifiant valide pour le namespace sélectionné.")}
 async function persistDraft(){if(draftId)return draftId;validateEvidence();const created=await api.createDiagnostic({vehicle_id:vehicleId,mileage:mileage?Number(mileage):null,symptoms,circumstances});await api.addFaultCodes(created.id,{fault_codes:parsedCodes.map(code=>({namespace,code,ecu:ecu||null,status,freeze_frame:{}}))});for(const item of measurements){const numeric=Number(item.value);await api.addMeasurement(created.id,{name:item.name,value:Number.isFinite(numeric)&&item.value.trim()?numeric:item.value,unit:item.unit||null,conditions:item.conditions,source:"manual"})}for(let index=0;index<images.length;index++){const item=images[index];const data=new FormData();data.append("files",item.file);data.append("category",item.category);data.append("description",item.description);await api.uploadImages(created.id,data);setUploadProgress(Math.round(((index+1)/images.length)*100))}setDraftId(created.id);return created.id}
 async function saveEvidence(){setBusy(true);setError("");setNotice("");try{await persistDraft();setNotice("Preuves enregistrées. Le dossier est prêt pour le diagnostic assisté.")}catch(value){setError(value instanceof Error?value.message:"Enregistrement impossible")}finally{setBusy(false)}}
 async function launchAnalysis(){setBusy(true);setError("");setNotice("");try{const id=await persistDraft();await api.analyzeDiagnostic(id);router.push(`/diagnostics/ai/${id}`)}catch(value){setError(value instanceof Error?value.message:"Analyse impossible");setBusy(false)}}

 return <ProductLayout active={step} identity={account?`${account.email} · ${account.role}`:"Session atelier"}>
  {step===1&&<EntryScreen sessions={sessions} vehicles={vehicles} onStart={startNew}/>} 
  {step===2&&<div className="space-y-6"><SectionIntro label="02 / IDENTIFICATION DU VÉHICULE" title={<>Établir le contexte<br/>avant d’interpréter.</>} description="Le code ne suffit pas. Le moteur, le calculateur et la version logicielle déterminent si une définition est réellement applicable."/><FlowProgress active={2} onNavigate={navigate}/>{error&&<Alert message={error}/>} {notice&&<Notice message={notice}/>} 
   <div className="grid gap-6 xl:grid-cols-2"><section className="orvect-panel"><h2 className="text-2xl font-medium">Rechercher le véhicule</h2>
    <div className="mt-5"><label className="orvect-field-label" htmlFor="existing-vehicle">Véhicule déjà enregistré</label><select id="existing-vehicle" className="orvect-field" value={vehicleId} onChange={event=>setVehicleId(event.target.value)}><option value="">Sélectionner un véhicule</option>{vehicles.map(item=><option key={item.id} value={item.id}>{item.make} {item.model} · {item.engine_code||"configuration à confirmer"}</option>)}</select>{vehicleId&&<button type="button" className="orvect-button-primary mt-3" onClick={()=>setStep(3)}>Utiliser ce véhicule</button>}</div>
    <div className="my-6 flex items-center gap-3 text-[10px] uppercase text-orvect-alloy"><span className="h-px flex-1 bg-orvect-alloy"/>ou identifier<span className="h-px flex-1 bg-orvect-alloy"/></div><div className="mb-4 flex gap-2"><button type="button" onClick={()=>setIdentifierMode("registration")} className={identifierMode==="registration"?"orvect-button-primary":"orvect-button-secondary"}>Immatriculation</button><button type="button" onClick={()=>setIdentifierMode("vin")} className={identifierMode==="vin"?"orvect-button-primary":"orvect-button-secondary"}>VIN</button></div>
    <form onSubmit={identify} className="space-y-4">{identifierMode==="registration"?<div className="grid gap-3 sm:grid-cols-[1fr_120px]"><Field label="Immatriculation"><input className="orvect-field uppercase" required value={registration} onChange={event=>setRegistration(event.target.value)} placeholder="AA-123-BB"/></Field><Field label="Pays"><select className="orvect-field" value={country} onChange={event=>setCountry(event.target.value)}><option>FR</option><option>BE</option><option>CH</option><option>LU</option></select></Field></div>:<Field label="VIN ou numéro de châssis"><input className="orvect-field uppercase" required minLength={11} maxLength={17} value={vin} onChange={event=>setVin(event.target.value)} placeholder="17 caractères"/><p className="mt-2 text-xs text-slate-500">Chiffré au repos · affichage toujours masqué.</p></Field>}<button className="orvect-button-primary" disabled={busy}>{busy?"Vérification…":"Vérifier l’identification"}</button></form>
    {lookup?.candidates?.length?<div className="mt-6 space-y-3"><p className="orvect-label">CONFIGURATIONS TROUVÉES</p>{lookup.candidates.map(candidate=><label key={candidate.id} className="flex cursor-pointer gap-3 border border-orvect-alloy p-4"><input type="radio" name="candidate" checked={candidateId===candidate.id&&!manualOpen} onChange={()=>{setCandidateId(candidate.id);setManualOpen(false)}}/><span><strong>{candidate.make} {candidate.model} · {candidate.model_year??"année inconnue"}</strong><span className="mt-1 block text-sm text-slate-600">{candidate.engine_code||"code moteur manquant"} · {candidate.transmission_type||"boîte à confirmer"}</span><span className="mt-2 block text-[10px] uppercase text-slate-500">Source {candidate.provider_name} · confirmation humaine requise</span></span></label>)}<button type="button" className="text-sm underline" onClick={()=>setManualOpen(true)}>Aucune variante ne correspond</button></div>:null}
    {lookup?.resolution_id&&manualOpen?<fieldset className="mt-6 grid gap-3 border border-orvect-alloy p-4 sm:grid-cols-2"><legend className="px-2 text-sm font-medium">Données vérifiées manuellement</legend>{([['make','Marque *'],['model','Modèle *'],['model_year','Année'],['engine_code','Code moteur *'],['transmission_code','Code boîte'],['engine_power_hp','Puissance (ch)']] as [keyof ManualVehicle,string][]).map(([key,label])=><Field key={key} label={label}><input className="orvect-field" value={manual[key]} onChange={event=>setManual({...manual,[key]:event.target.value})}/></Field>)}</fieldset>:null}{lookup?.resolution_id?<button type="button" className="orvect-button-primary mt-5" disabled={busy||(!candidateId&&!manualOpen)} onClick={confirmVehicle}>{manualOpen?"Confirmer la saisie manuelle":"Confirmer ce véhicule"}</button>:null}
   </section><VehicleContext vehicle={vehicle} lookup={lookup}/></div>
  </div>}

  {step===3&&<div className="space-y-6"><SectionIntro label="03 / PROBLÈME & PREUVES" title={<>Décrire ce qui se passe.<br/>Conserver ce qui le prouve.</>} description="Chaque observation reste distinguée d’une hypothèse. Une mesure conserve sa valeur, son unité, sa méthode et ses conditions."/><FlowProgress active={3} onNavigate={navigate}/>{error&&<Alert message={error}/>} {notice&&<Notice message={notice}/>}<fieldset disabled={Boolean(draftId)} className="grid gap-6 xl:grid-cols-2 disabled:opacity-70">
   <section className="orvect-panel space-y-4"><h2 className="text-2xl font-medium">Problème observé</h2><Field label="Motif client / symptômes"><textarea className="orvect-field min-h-24" value={symptoms} onChange={event=>setSymptoms(event.target.value)} placeholder="Ex. perte de puissance intermittente"/><p className="mt-1 text-xs text-slate-500">Texte rapporté · non vérifié tant qu’il n’est pas constaté</p></Field><Field label="Conditions d’apparition"><textarea className="orvect-field min-h-20" value={circumstances} onChange={event=>setCircumstances(event.target.value)} placeholder="Moteur chaud, sous charge, régime…"/></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Namespace"><select className="orvect-field" value={namespace} onChange={event=>setNamespace(event.target.value)}><option value="sae_obd2">SAE / OBD-II</option><option value="vag_uds">VAG / UDS</option></select></Field><Field label="Kilométrage"><input className="orvect-field" type="number" min="0" value={mileage} onChange={event=>setMileage(event.target.value)}/></Field></div><div className="orvect-panel-dark"><label htmlFor="fault-codes" className="orvect-field-label text-orvect-alloy">Code défaut</label><input id="fault-codes" className="orvect-field border-white/30 bg-orvect-graphite font-mono uppercase text-orvect-mineral" value={codes} onChange={event=>setCodes(event.target.value)} placeholder={namespace==="sae_obd2"?"P0301":"Identifiant VAG / UDS documenté"}/><p className="mt-3 text-xs text-orvect-alloy">Aucune définition n’est inventée à partir de la famille numérique.</p></div><div className="grid gap-3 sm:grid-cols-2"><Field label="Calculateur"><input className="orvect-field" value={ecu} onChange={event=>setEcu(event.target.value)} placeholder="Référence ou module"/></Field><Field label="Statut"><select className="orvect-field" value={status} onChange={event=>setStatus(event.target.value)}><option value="unknown">Inconnu</option><option value="active">Actif</option><option value="intermittent">Intermittent</option><option value="stored">Mémorisé</option></select></Field></div>{parsedCodes.length>0&&<div className="flex flex-wrap gap-2">{parsedCodes.map(code=><span key={code} className="border border-orvect-alloy px-3 py-2 font-mono text-sm">{code}</span>)}</div>}</section>
   <section className="orvect-panel space-y-4"><h2 className="text-2xl font-medium">Preuves techniques</h2><div className="grid gap-3 sm:grid-cols-2"><Field label="Mesure"><input className="orvect-field" value={measure.name} onChange={event=>setMeasure({...measure,name:event.target.value})} placeholder="Pression rail"/></Field><Field label="Valeur / unité"><div className="flex"><input className="orvect-field" value={measure.value} onChange={event=>setMeasure({...measure,value:event.target.value})} placeholder="Valeur"/><input className="orvect-field w-24 border-l-0" value={measure.unit} onChange={event=>setMeasure({...measure,unit:event.target.value})} placeholder="bar"/></div></Field></div><Field label="Méthode et conditions"><input className="orvect-field" value={measure.conditions} onChange={event=>setMeasure({...measure,conditions:event.target.value})} placeholder="Outil, régime, température…"/></Field><button type="button" className="orvect-button-secondary" onClick={addMeasurement}>Ajouter la mesure</button>{measurements.map((item,index)=><div key={`${item.name}-${index}`} className="flex justify-between border border-orvect-alloy p-3 text-sm"><span>{item.name} · <strong>{item.value} {item.unit}</strong><small className="mt-1 block text-slate-500">{item.conditions||"conditions non renseignées"}</small></span><button type="button" onClick={()=>setMeasurements(rows=>rows.filter((_,i)=>i!==index))} className="text-xs underline">Retirer</button></div>)}
    <Field label="Document / photo"><label htmlFor="images" className="flex min-h-24 cursor-pointer items-center justify-center border border-dashed border-orvect-alloy p-4 text-center text-sm">JPEG, PNG ou WebP · 10 Mio maximum</label><input id="images" type="file" className="sr-only" accept="image/jpeg,image/png,image/webp" multiple onChange={event=>event.target.files&&addImages(event.target.files)}/></Field>{images.map((item,index)=><div key={item.preview} className="flex items-center gap-3 border border-orvect-alloy p-3"><img src={item.preview} alt="Aperçu de la preuve" className="h-14 w-14 object-cover"/><span className="min-w-0 flex-1 truncate text-sm">{item.file.name}</span><button type="button" onClick={()=>removeImage(index)} className="text-xs underline">Retirer</button></div>)}<SourceLabel title="SOURCE / SAISIE TECHNICIEN">source_id généré à la persistance · source_type: observation atelier<br/>horodatage automatique · compatibilité liée au véhicule du dossier</SourceLabel><div><p className="orvect-label">ÉTAT DU TEST</p><p className="mt-2 text-sm leading-6">POSITIVE · NEGATIVE · INCONCLUSIVE<br/>UNAVAILABLE · INVALID · REFUSED</p></div><StatusLabel>UNAVAILABLE / N’ALTÈRE PAS L’ÉTAT DIAGNOSTIQUE</StatusLabel></section>
  </fieldset><div className="flex flex-col gap-3 sm:flex-row"><button type="button" className="orvect-button-primary min-w-[240px]" disabled={busy} onClick={saveEvidence}>{busy?"Enregistrement…":"Enregistrer les preuves"}</button><button type="button" className="orvect-button-secondary min-w-[260px]" disabled={busy} onClick={launchAnalysis}>{busy?`Traitement${uploadProgress?` · ${uploadProgress}%`:""}`:"Passer au diagnostic assisté"}</button></div><p className="text-xs text-slate-500">Seuls les résultats réellement informatifs peuvent modifier l’état diagnostique. Une connaissance sans provenance reste NON VÉRIFIÉE.</p></div>}
 </ProductLayout>
}

function EntryScreen({sessions,vehicles,onStart}:{sessions:Session[];vehicles:Vehicle[];onStart:()=>void}){const recent=sessions.slice(0,3);return <div className="space-y-6"><SectionIntro label="01 / ENTRÉE ATELIER" title={<>Que voulez-vous<br/>diagnostiquer&nbsp;?</>} description="Démarrez un nouveau dossier ou reprenez un diagnostic existant. Le garage actif vient de votre session authentifiée."/><FlowProgress active={1}/><div className="grid gap-6 xl:grid-cols-2"><section className="orvect-panel-dark min-h-[280px]"><p className="orvect-label text-orvect-alloy">NOUVEAU DOSSIER</p><h2 className="mt-5 text-4xl font-bold leading-tight tracking-[-.04em]">Commencer par<br/>le véhicule.</h2><p className="mt-5 max-w-lg text-sm leading-6 text-orvect-alloy">VIN protégé, saisie manuelle possible et aucune hypothèse avant d’avoir établi le contexte minimum.</p><button type="button" className="orvect-button-primary mt-6 min-w-[240px]" onClick={onStart}>Identifier un véhicule</button></section><section className="orvect-panel"><p className="orvect-label text-slate-500">DOSSIERS RÉCENTS</p><div className="mt-4 space-y-3">{recent.length?recent.map(item=>{const vehicle=vehicles.find(row=>row.id===item.vehicle_profile_id);return <Link key={item.id} href={`/diagnostics/ai/${item.id}`} className="flex items-start justify-between gap-3 border border-orvect-alloy p-4 hover:border-orvect-orange"><span><strong className="block">{vehicle?`${vehicle.make} ${vehicle.model}`:"Véhicule"} · #{item.id.slice(0,8)}</strong><span className="mt-1 block text-xs text-slate-500">{new Date(item.created_at).toLocaleString("fr-FR")}</span></span><span className="text-[10px] uppercase">{item.status.replaceAll("_"," ")}</span></Link>}):<div className="border border-orvect-alloy p-4 text-sm text-slate-500">Aucun dossier récent dans ce garage.</div>}</div></section></div><p className="orvect-label text-orvect-alloy">PROTOTYPE TECHNIQUE · AUCUN RÉSULTAT MESURÉ OU PARTENARIAT OEM REVENDIQUÉ</p></div>}
function VehicleContext({vehicle,lookup}:{vehicle?:Vehicle;lookup:VehicleResolveResult|null}){const candidate=lookup?.candidates?.[0];return <section className="orvect-panel-dark"><p className="orvect-label text-orvect-alloy">CONTEXTE TECHNIQUE</p><h2 className="mt-5 text-4xl font-bold leading-tight tracking-[-.04em]">{vehicle?`${vehicle.make} ${vehicle.model}`:candidate?.model||"Véhicule"}<br/>{vehicle?.engine_code?"Configuration identifiée":"Configuration incomplète"}</h2><div className="mt-5"><StatusLabel>{vehicle?.engine_code?"CONFIGURATION CONFIRMÉE":"VEHICLE CONFIGURATION NOT SUFFICIENTLY IDENTIFIED"}</StatusLabel></div><div className="mt-6 text-sm leading-6"><p className="orvect-label text-orvect-alloy">DONNÉES CRITIQUES</p><ul className="mt-3"><li>• Code moteur : {vehicle?.engine_code||candidate?.engine_code||"à confirmer"}</li><li>• Référence ECU : à relever pendant le scan</li><li>• Version logicielle : à relever pendant le scan</li><li>• Marché / année modèle : {vehicle?.model_year??candidate?.model_year??"à confirmer"}</li></ul></div><p className="mt-6 text-sm text-orvect-alloy">Aucun DTC constructeur n’est interprété tant que la compatibilité véhicule n’est pas établie.</p></section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="orvect-field-label">{label}</span>{children}</label>}
function Alert({message}:{message:string}){return <div role="alert" className="border border-red-600 bg-red-50 p-4 text-sm text-red-800"><strong>Action impossible.</strong> {message}</div>}
function Notice({message}:{message:string}){return <div role="status" className="border border-orvect-orange bg-orange-50 p-4 text-sm">{message}</div>}
