"""Run real Gemini on synthetic varied DTC cases; persists test cases and a report.
Requires the local backend configured with Gemini + DIAGNOSTIC_EXPLORATION_ENABLED.
Does not read or print API keys. Consumes real provider calls.
"""
import argparse,json,time
from pathlib import Path
from urllib.request import Request,urlopen
from urllib.error import HTTPError

ROOT=Path(__file__).resolve().parents[1]

def main():
    parser=argparse.ArgumentParser()
    parser.add_argument('--api',default='http://127.0.0.1:3000/backend-api')
    parser.add_argument('--output',default=str(ROOT/'.local/exploratory-gemini-report.json'))
    args=parser.parse_args()
    def call(path,payload=None):
        req=Request(args.api+path,data=json.dumps(payload).encode() if payload is not None else None,headers={'Content-Type':'application/json'})
        with urlopen(req,timeout=240) as response:return json.load(response)
    fixture=json.loads((ROOT/'frontend/public/demo/golf-misfire.json').read_text())
    specs=[
        ('P0171','sae_obd2','Ralenti instable à chaud, corrections carburant positives signalées ; pas de valeur constructeur disponible.'),
        ('P1351','vag_obd','Démarrage difficile et ralenti irrégulier à froid. Définition constructeur non disponible pour ce véhicule.'),
        ('U0100','sae_obd2','Démarrage intermittent et perte de communication du lecteur avec le calculateur moteur.'),
        ('P1FFF','vag_obd','Code volontairement choisi sans définition disponible. Ralenti irrégulier et vibrations ; aucune interprétation du code présupposée.'),
        ('P0301+P0351','sae_obd2','Ratés au ralenti, vibrations et voyant moteur. Les relevés synthétiques sont concentrés sur le cylindre 1.'),
    ]
    results=[]
    report={'synthetic':True,'api':args.api,'started_at':time.strftime('%Y-%m-%dT%H:%M:%S%z'),'results':results}
    output=Path(args.output);output.parent.mkdir(parents=True,exist_ok=True)
    def save():output.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
    for codes,namespace,symptoms in specs:
        started=time.monotonic();row={'codes':codes,'namespace':namespace};results.append(row)
        try:
            case=call('/diagnostics',{'vehicle_id':fixture['vehicle_id'],'mileage':86420,'symptoms':'DÉMONSTRATION SYNTHÉTIQUE — TEST GEMINI EXPLORATOIRE. '+symptoms,'circumstances':'Scénario simulé en atelier, aucun véhicule réel.'})
            path='/diagnostics/'+case['id'];row['case_id']=case['id'];row['url']='http://127.0.0.1:3000/diagnostics/ai/'+case['id']
            call(path+'/fault-codes',{'fault_codes':[{'code':code,'namespace':namespace,'ecu':'ECU moteur','status':'active','freeze_frame':{},'technician_verification':'confirmed','technician_note':'Code relu du scénario synthétique ; interprétation éventuelle non vérifiée.'} for code in codes.split('+')]})
            if '+' in codes:
                for measurement in fixture['measurements']:call(path+'/measurements',measurement)
            analysis=call(path+'/analyze',{})
            detail=call(path)
            row.update(model=detail['case']['ai_model'],meanings=analysis['interpretedFaultCodes'],hypotheses=[h['label'] for h in analysis['hypotheses']],next_checks=[h['title'] for h in analysis['nextChecks']],conclusion=analysis['finalConclusion'],warnings=analysis['warnings'])
            assert row['model'].startswith('gemini-'), 'Not generated by Gemini'
            assert any('MODE EXPLORATOIRE' in warning for warning in analysis['warnings'])
            assert analysis['safetyAssessment']['decisionSource']=='safety_engine'
            assert all(h['verificationStatus']=='unverified' for h in analysis['hypotheses'])
            assert analysis['nextChecks'], 'No follow-up checks'
            assert analysis['hypotheses'], 'No hypotheses despite synthetic symptoms'
            row['passed']=True
            if '+' in codes:
                call(path+'/measurements',{'name':'Inspection connecteur bobine 1','value':'SIMULATION : verrou cassé, connecteur partiellement débranché','unit':None,'conditions':'Observation synthétique, contact coupé, moteur refroidi','source':'manual'})
                updated=call(path+'/reanalyze',{})
                row['follow_up_hypotheses']=[h['label'] for h in updated['hypotheses']]
                row['follow_up_changed']=updated!=analysis
                assert row['follow_up_changed'] and updated['hypotheses'],'New evidence did not produce an updated result'
        except HTTPError as exc:
            row.update(passed=False,error=f'HTTP {exc.code}: '+exc.read().decode()[:400])
        except Exception as exc:
            row.update(passed=False,error=str(exc)[:400])
        row['duration_seconds']=round(time.monotonic()-started,1);save()
        print(json.dumps({k:row[k] for k in ('codes','passed','model','hypotheses','error','duration_seconds') if k in row},ensure_ascii=False),flush=True)
    report['passed']=all(row.get('passed') for row in results);save()
    print('Report: '+str(output),flush=True)
    raise SystemExit(0 if report['passed'] else 1)

if __name__=='__main__':main()
